#pragma config(Sensor, in1,    sigueLinea,   sensorLineFollower)
#pragma config(Sensor, in2,    regulador,  sensorPotentiometer)
#pragma config(Sensor, in3,    fotoSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  botonFin,    sensorTouch)
#pragma config(Sensor, dgtl2,  boton,     sensorTouch)
#pragma config(Sensor, dgtl3,  cuentaVueltas,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl12, led,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           motorIzquierdo,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port8,           linterna,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          motorDerecho,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "robotx.h"	//Includes the RobotX library

task main()
{
	while (true)	//Infinite loop / Bucle infinito
	{
		// SPANISH COMMANDS (Ponga su codigo aqui)
		ponMotor(motorIzquierdo, 90);	//Enciende Motor Izquierdo con velocidad 90
		espera(2);										//Espera 2 segundos
		paraMotor(motorIzquierdo);		//Para el motor Izquierdo
		espera(2);										//Espera 2 segundos
		retrocede(50);								//Retrocede con velocidad 50
		espera(2);										//Espera 2 segundos
		giroIzquierdaTiempo(90, 2);		//Gira a la izquierda con velocidad 90 durante 2 segundos y después para
		giroDerechaTiempo(90, 2);			//Gira a la derecha con velocidad 90 durante 2 segundos y después para
		avanzaTiempo(95, 2);					//Avanza con una velocidad de 95 durante 2 segundos y después para
		giroRapido(-50, 3); 					//Giro rapido hacia la izquierda (negativo) durante 3 segundos y despues para
		giroRapido(50, 3); 						//Giro rapido hacia la derecha (positivo) durante 3 segundos y despues para
		para();												//Para los motores izquierdo y derecho
		paraRobot();									//Igual que para, para los motores izquierdo y derecho
		
		// ENGLISH COMMANDS (Put your code here)
		startMotor(LEFT_MOTOR, 90);		//Start left motor with a speed of 90
		wait(2);											//Wait 2 seconds
		stopMotor(LEFT_MOTOR);				//It stops the leftMotor
		wait(2);											//Wait 2 seconds
		goBackwards(50);							//Go backwards with a speed of 50	
		wait(2);											//Wait 2 seconds
		timedSwingTurnToLeft(90, 2);	//Turn to the left with a speed of 90 during 2 seconds and then, it stops.
		timedSwingTurnToRight(90,2);	//Turn to the right with a speed of 90 during 2 seconds and then, it stops.
		timedGoForward(95, 2);				//Go forward with a speed of 95 during 2 seconds and then, it stops.
		timedPointTurn(-50, 3);				//Quick turn to the left (negative value) during 3 seconds and then, it stops.
		timedPointTurn(50, 3);				//Quick turn to the right (positive value) during 3 seconds and then, it stops.
		stopRobot();									//It stops motors left and right.
	}
}
