#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "robotx.h"	//Includes the RobotX

task main()
{
	//Write your code here!
  timedGoForward(95, 2);  			// Go forward with a speed of 95 during 2 seconds.
  timedPointTurn(-50, 2); 			// Rotate on point counterclockwise during 1 second.
	timedSwingTurnToRight(90, 2); // Turn to the right with a speed of 90 during 2 seconds.
	timedSwingTurnToLeft(90, 2);	// Turn to the left with a speed of 90 during 2 seconds.
}
