#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "robotx.h"	//Includes the RobotX

/*
	Project name: Labyrinth Challenge
	Author: Jose Luis Cebrian Marquez (Template) and [your name here!]
	Team members:
	Period:
*/


task main()
{
	//Write your code here!
  wait(1); // Wait for 1 second until we start
  timedGoForward(95, 2);  // Go forward with a speed of 95 during 2 seconds.
  timedPointTurn(-50, 1); // Rotate on point counterclockwise during 1 second.
  timedGoForward(95, 2);
  timedPointTurn(50, 1);
  timedGoForward(50, 1.5);
  timedPointTurn(50, 1);
  timedGoForward(50, 1.5);
}
