#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	Project name: Labyrinth Challenge
	Author: Jose Luis Cebrian Marquez (Template) and [your name here!]
	Team members: 
	Period: 
*/

// Function to Turn In Point at a certain SPEED during TIME
// Rotation to the right (clockwise) with positive values
// and to the left (counteclockwise) with negative values
void turnInPoint(signed byte speed = 95, int time)
{
  motor[leftMotor] = speed;
  motor[rightMotor] = -speed;
  wait(time);
  motor[leftMotor] = motor[rightMotor] = 0;
}

// Function to Turn to the LEFT a certain SPEED during TIME
void swingTurnToLeft(signed byte speed = 95, int time)
{
  motor[leftMotor] = 0;
  motor[rightMotor] = abs(speed);
  wait(time);
  motor[leftMotor] = motor[rightMotor] = 0;
}


// Function to Turn to the RIGHT a certain SPEED during TIME
void swingTurnToRight(signed byte speed = 95, int time)
{
  motor[leftMotor] = abs(speed);
  motor[rightMotor] = 0;
  wait(time);
  motor[leftMotor] = motor[rightMotor] = 0;
}

// Function to Go Forward at a certain SPEED during TIME seconds.
// Use a negative speed to go backwards.
void goForward(signed byte speed = 95, int time)
{
  motor[leftMotor] = motor[rightMotor] = speed;
  wait(time);
  motor[leftMotor] = motor[rightMotor] = 0;
}

// Functions in Spanish (delete this block if you do not need it)

// Giro Rapido hace un giro rapido hacia la derecha (sentido de las agujas del reloj)
// o hacia la izquierda (sentido contrario a las agujas del reloj)
// El giro es producido durante el tiempo indicado por time
void giroRapido(signed byte velocidad = 95, int tiempo)
{
  turnInPoint(velocidad, tiempo);
}

// Avanzar hacia delante (o hacia atras si la velocidad es negativa)
void avanzar(signed byte velocidad = 95, int tiempo)
{
  goForward(velocidad, tiempo);
}

// Giro a la izquierda con Velocidad y Tiempo
void giroIzquierda(signed byte velocidad = 95, int tiempo)
{
 swingTurnToLeft(velocidad, tiempo);
} 

// Giro a la derecha con Velocidad y Tiempo
void giroDerecha(signed byte velocidad = 95, int tiempo)
{
 swingTurnToRight(velocidad, tiempo);
} 


// END of the "Functions in Spanish"

task main()
{
	//Write your code here!
  wait(1); // Wait for 1 second until we start
	goForward(95, 2);
	turnInPoint(-50, 1);
	goForward(95, 2);
	turnInPoint(50, 1);
	goForward(50, 1.5);
	turnInPoint(50, 1);
	goForward(50, 1.5);
}
