#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	Project name: Labyrinth Challenge
	Author: Jose Luis Cebrian Marquez (Template) and 
	Team members: 
	Period: 
*/

// Function to Turn In Place at a certain SPEED during TIME
// Rotation to the right (clockwise) with positive values
// and to the left (counteclockwise) with negative values
void turnInPlace(signed byte speed = 95, int time)
{
	motor[leftMotor] = speed;
  motor[rightMotor] = -speed;
  wait(time);
  motor[leftMotor] = motor[rightMotor] = 0;
}

// Function to Go Forward at a certain SPEED during TIME seconds.
// Use a negative speed to go backwards.
void goForward(signed byte speed = 95, int time)
{
	motor[leftMotor] = motor[rightMotor] = speed;
  wait(time);
  motor[leftMotor] = motor[rightMotor] = 0;
}

task main()
{
	//Write your code here!
  wait(1); // Wait for 1 second until we start
	goForward(95, 2);
	turnInPlace(-50, 1);
	goForward(95, 2);
	turnInPlace(50, 1);
	goForward(50, 1.5);
	turnInPlace(50, 1);
	goForward(50, 1.5);
}
